// Outlines the wordmark letters from Fredoka Bold into src/game/art/brand-glyphs.js,
// so the logo draws the same in the game and in exported files with no font loaded.
// Run after changing the letters: node scripts/brand-glyphs.mjs
import { readFileSync, writeFileSync } from "node:fs";
import opentype from "opentype.js";

const SIZE = 100; // em size; the logo scales from here
const SETS = { GLYPHS: [700, "Luna'sLullaby"], TAG_GLYPHS: [700, "a cozy little farming life"] };

// Own serializer: opentype's toPathData can glue numbers together ("18.7 0" -> "18.70").
const n = (v) => String(Math.round(v * 10) / 10);
const pathData = (p) =>
  p.commands
    .map((c) => {
      const pts = c.type === "Z" ? [] : c.type === "Q" ? [c.x1, c.y1, c.x, c.y] : c.type === "C" ? [c.x1, c.y1, c.x2, c.y2, c.x, c.y] : [c.x, c.y];
      return c.type + pts.map(n).join(" ");
    })
    .join("");

function outline(weight, chars) {
  const buf = readFileSync(`node_modules/@fontsource/fredoka/files/fredoka-latin-${weight}-normal.woff`);
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const glyphs = {};
  for (const ch of new Set(chars)) {
    const g = font.charToGlyph(ch);
    glyphs[ch] = { d: pathData(g.getPath(0, 0, SIZE)), adv: Math.round((g.advanceWidth / font.unitsPerEm) * SIZE * 10) / 10 };
  }
  return JSON.stringify(glyphs).replace(/\},"/g, '},\n  "').replace(/^\{/, "{\n  ").replace(/\}\}$/, "}\n}");
}

let out = `// Generated by scripts/brand-glyphs.mjs from Fredoka Bold (SIL OFL 1.1). Do not edit.\n// Em size ${SIZE}; y is baseline-relative (negative is up).\n`;
for (const [name, [weight, chars]] of Object.entries(SETS)) out += `export const ${name} = ${outline(weight, chars)};\n`;
writeFileSync("src/game/art/brand-glyphs.js", out);
console.log(out.length, "bytes");
